id: I6E97A70A
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:02:52.664129
last_modified: 2023-02-09 15:02:52.664251
source_metadata:
  title: 'MSV 1,03: Pravāraṇāvastu'
  language: sa
bases:
  D06A:
    base_file: D06A.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
